apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "consumer-application-sts"
  namespace: kafkastreamingdata
  labels:
    app: "consumer-application-sts"
spec:
  selector:
    matchLabels:
      app: "consumer-application-sts"     # This selector matches the pod labels defined below
        # serviceName: "consumer-application-headless-svc" # This should correspond to a headless service name, if used
  replicas: 1
  podManagementPolicy: Parallel
    # minReadySeconds: 10
  template:
    metadata:
      labels:
        app: "consumer-application-sts"   # Labels here must match spec.selector.matchLabels
    spec:
      initContainers:
        - name: volume-permission-fix
          image: alpine
          command: ["sh", "-c", "chown -R 1000:1000 /app/consumer-app-data && chown -R 1000:1000 /app/app-merge-data"]
          volumeMounts:
          - name: consumer-app-data
            mountPath: /app/consumer-app-data
          - name: app-merge-data
            mountPath: /app/app-merge-data
      containers:
        - name: "consumer-container"
          image: sjafari2/kafkaconsumer:latest
          securityContext:
            runAsUser: 1000  # UID for sjafari
            runAsGroup: 1000 # GID for sjafari
          env:
          - name: POD_ORDINAL
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              sleep infinity
          ports:
          - containerPort: 8080
            name: "consumer-port"
          - containerPort: 9093
            name: "consumer-exporter-port"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
          - mountPath: app/consumer-app-data
            name: consumer-app-data
           #      restartPolicy: OnFailure
        - name: "application-container"
          image: sjafari2/kafkaapplication:latest
          securityContext:
            runAsUser: 1000  # UID for sjafari
            runAsGroup: 1000 # GID for sjafari
          ports:
          - containerPort: 8081
            name: "application-port"
          - containerPort: 9094
            name: "application-exporter-port"
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf app/app-merge-data/*
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              sleep infinity
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
          volumeMounts:
          - mountPath: app/consumer-app-data
            name: consumer-app-data
          - mountPath: app/app-merge-data
            name: app-merge-data
              # volumes:
              #  - name: consumer-app-data
              # emptyDir: {}  # Use emptyDir for temporary storage
              #  - name: app-merge-data
              #persistentVolumeClaim:
              #claimName: app-merge-data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - dtn-01.nrp.mghpcc.org  
 
  volumeClaimTemplates:
    - metadata:
        name: consumer-app-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "rook-cephfs-central"
        resources:
          requests:
            storage: "5Gi"
    - metadata:
        name: app-merge-data
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: "rook-cephfs-central"
        resources:
          requests:
            storage: "5Gi"
    #      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - cons-sts
#                - merge-sts
#                - prod-sts
#                - kafka
#                - kafka-zookeeper
#            topologyKey: "kubernetes.io/hostname"
