apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consumer-application-sts
  namespace: kafkastreamingdata
  labels:
    app: consumer-application-sts
spec:
  serviceName: cons-app-headless-svc  # Added serviceName field for StatefulSet
  selector:
    matchLabels:
      app: consumer-application-sts
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: consumer-application-sts
    spec:
      initContainers:
        - name: volume-permission-fix
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /app || true"]
          volumeMounts:
            - name: consumer-app-data
              mountPath: /app/consumer-app-data
            - name: app-merge-data
              mountPath: /app/app-merge-data
      containers:
        - name: consumer-container
          image: sjafari2/kafkaconsumer:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: POD_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              sleep infinity
          ports:
            - containerPort: 8080
              name: consumer-port
            - containerPort: 9093
              name: cons-exp-port
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: consumer-app-data
              mountPath: /app/consumer-app-data

        - name: application-container
          image: sjafari2/kafkaapplication:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf /app/app-merge-data/*
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              sleep infinity
          ports:
            - containerPort: 8081
              name: app-port
            - containerPort: 9094
              name: app-exp-port
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
          volumeMounts:
            - name: consumer-app-data
              mountPath: /app/consumer-app-data
            - name: app-merge-data
              mountPath: /app/app-merge-data

      volumes:
        - name: consumer-app-data
          persistentVolumeClaim:
            claimName: consumer-app-data
        - name: app-merge-data
          persistentVolumeClaim:
            claimName: app-merge-data

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gpu-01.nrp.mghpcc.org

