apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "consumer-application-sts"
  namespace: kafkastreamingdata
  labels:
    app: "consumer-application-sts"
spec:
  selector:
    matchLabels:
      app: "consumer-application-sts"
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: "consumer-application-sts"
    spec:
      initContainers:
        - name: volume-permission-fix
          image: alpine
          command: ["sh", "-c", "chown -R 1000:1000 /app/consumer-app-data && chown -R 1000:1000 /app/app-merge-data"]
          volumeMounts:
            - name: consumer-app-data
              mountPath: /app/consumer-app-data
            - name: app-merge-data
              mountPath: /app/app-merge-data
      containers:
        - name: "consumer-container"
          image: sjafari2/kafkaconsumer:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: POD_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              sleep infinity
          ports:
            - containerPort: 8080
              name: "consumer-port"
            - containerPort: 9093
              name: "cons-exp-port"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: consumer-app-data
              mountPath: /app/consumer-app-data
        - name: "application-container"
          image: sjafari2/kafkaapplication:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf /app/app-merge-data/*
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              sleep infinity
          ports:
            - containerPort: 8081
              name: "app-port"
            - containerPort: 9094
              name: "app-exp-port"
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
          volumeMounts:
            - name: consumer-app-data
              mountPath: /app/consumer-app-data
            - name: app-merge-data
              mountPath: /app/app-merge-data
      volumes:
        - name: consumer-app-data
          persistentVolumeClaim:
            claimName: consumer-app-data
        - name: app-merge-data
          persistentVolumeClaim:
            claimName: app-merge-data
      tolerations:
        - key: "nautilus.io/gitlab-issue"
          operator: "Equal"
          value: "1055"
          effect: "NoSchedule"
        - key: "nautilus.io/stashcache"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gpu-04.nrp.mghpcc.org

