apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consumer-sts
  namespace: kafkastreamingdata
  labels:
    app: consumer-sts
spec:
  serviceName: consumer-headless-svc
  selector:
    matchLabels:
      app: consumer-sts
  replicas: 2
  podManagementPolicy: Parallel

  template:
    metadata:
      labels:
        app: consumer-sts
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - patternlab.calit2.optiputer.net

      initContainers:
        - name: bootstrap-consumer
          image: sjafari2/kafkaconfluentconsumer:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "[init] Bootstrapping config and code..."
              mkdir -p /config
              echo "[init] Copying all files from /defaults to /config..."
              cp /defaults/pipeline-configmap.yaml /config/pipeline-configmap.yaml
              chown -R 1000:1000 /config
              chmod -R u+w /config

              if [ ! -f /app/consumer-merge-data/.code_initialized ]; then
                echo "[init] Copying code to /app/consumer-merge-data..."
                cp -r /code/* /app/consumer-merge-data/
                touch /app/consumer-merge-data/.code_initialized
              fi
              chown -R 1000:1000 /app/consumer-merge-data
              chmod -R u+w /app/consumer-merge-data
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: consumer-merge-data
              mountPath: /app/consumer-merge-data
            - name: shared-config
              mountPath: /config
            - name: config-default
              mountPath: /defaults

      containers:
        - name: consumer-container
          image: sjafari2/kafkaconfluentconsumer:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          workingDir: /app/consumer-merge-data
          env:
            - name: POD_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf ./logs/*
              mkdir -p ./logs
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              echo "Loaded config files:"
              ls -l /config
              cat /config/pipeline-configmap.yaml || echo "Config file not found"
              sleep infinity
          ports:
            - containerPort: 8080
              name: consumer-port
            - containerPort: 9093
              name: cons-exp-port

          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "1000Mi"
              cpu: "2000m"

          volumeMounts:
            - name: consumer-merge-data
              mountPath: /app/consumer-merge-data
            - name: shared-config
              mountPath: /config
            - name: config-default
              mountPath: /defaults
      volumes:
        - name: consumer-merge-data
          persistentVolumeClaim:
            claimName: consumer-merge-data
        - name: shared-config
          persistentVolumeClaim:
            claimName: pipeline-configmap-pvc
        - name: config-default
          configMap:
            name: pipeline-configmap
            items:
              - key: pipeline-configmap.yaml
                path: pipeline-configmap.yaml

