apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "merge-sts"
  namespace: "kafkastreamingdata"
  labels:
    app: "merge-sts"
spec:
  selector:
    matchLabels:
      app: "merge-sts"
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: "merge-sts"
    spec:
      initContainers:
        - name: volume-permission-fix
          image: alpine
          command: ["sh", "-c", "chown -R 1000:1000 /app/app-merge-data && chown -R 1000:1000 /app/merged-clstr-data"]
          volumeMounts:
            - name: app-merge-data
              mountPath: /app/app-merge-data
            - name: merged-clstr-data
              mountPath: /app/merged-clstr-data
      containers:
        - name: "merge-container"
          image: sjafari2/kafkamerge:latest
          env:
            - name: POD_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              sleep infinity
          ports:
            - containerPort: 8080
              name: "merge-port"
            - containerPort: 9093
              name: "merge-exp-port"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: app-merge-data
              mountPath: /app/app-merge-data
            - name: merged-clstr-data
              mountPath: /app/merged-clstr-data
      volumes:
        - name: app-merge-data
          persistentVolumeClaim:
            claimName: app-merge-data
        - name: merged-clstr-data
          persistentVolumeClaim:
            claimName: merged-clstr-data
      tolerations:
        - key: "nautilus.io/gitlab-issue"
          operator: "Equal"
          value: "1055"
          effect: "NoSchedule"
        - key: "nautilus.io/stashcache"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gpu-04.nrp.mghpcc.org

