apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: merge-sts
  namespace: kafkastreamingdata
  labels:
    app: merge-sts
spec:
  serviceName: merge-headless-svc
  selector:
    matchLabels:
      app: merge-sts
  replicas: 1
  restartPolicy: Always
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: merge-sts
    spec:
      initContainers:
        - name: volume-permission-and-bootstrap
          image: sjafari2/kafkaconfluentmerge:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "[init] Setting permissions on target dirs..."
              chown -R 1000:1000 /app/app-merge-data && chmod -R u+w /app/app-merge-data
              chown -R 1000:1000 /app/merged-data && chmod -R u+w /app/merged-data

              echo "[init] Bootstrapping config if needed..."
              if [ ! -f /config/pipeline-configmap.yaml ]; then
                cp /defaults/pipeline-configmap.yaml /config/pipeline-configmap.yaml
              fi

              echo "[init] Bootstrapping merge code if not present..."
              if [ ! -f /app/merged-data/.code_initialized ]; then
                cp -r /code/* /app/merged-data/
                touch /app/merged-data/.code_initialized
                chown -R 1000:1000 /app/merged-data
                chmod -R u+w /app/merged-data
              fi
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: app-merge-data
              mountPath: /app/app-merge-data
            - name: merged-data
              mountPath: /app/merged-data
            - name: shared-config
              mountPath: /config
            - name: config-default
              mountPath: /defaults

      containers:
        - name: merge-container
          image: sjafari2/kafkaconfluentmerge:latest
          env:
            - name: POD_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          workingDir: /app/merged-data
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              echo "Loaded config file contents:"
              cat /config/pipeline-configmap.yaml
              sleep infinity
          ports:
            - containerPort: 8080
              name: merge-port
            - containerPort: 9093
              name: merge-exp-port
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: app-merge-data
              mountPath: /app/app-merge-data
            - name: merged-data
              mountPath: /app/merged-data
            - name: shared-config
              mountPath: /config

      volumes:
        - name: app-merge-data
          persistentVolumeClaim:
            claimName: app-merge-data
        - name: merged-data
          persistentVolumeClaim:
            claimName: merged-data
        - name: shared-config
          persistentVolumeClaim:
            claimName: pipeline-configmap-pvc
        - name: config-default
          configMap:
            name: pipeline-configmap
            items:
              - key: pipeline-configmap.yaml
                path: pipeline-configmap.yaml

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gpu-01.nrp.mghpcc.org

