apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: request-sts
  namespace: kafkastreamingdata
  labels:
    app: request-sts
spec:
  serviceName: request-headless-svc
  selector:
    matchLabels:
      app: request-sts
  replicas: 1
  restartPolicy: Always
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: request-sts
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: volume-permission-and-bootstrap
          image: sjafari2/kafkaconfluentrequest:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "[init] Setting up permissions and bootstrapping code..."
              chown -R 1000:1000 /app/request-data && chmod -R u+w /app/request-data
              chown -R 1000:1000 /app/request-producer-data && chmod -R u+w /app/request-producer-data

              mkdir -p /config
              cp /defaults/pipeline-configmap.yaml /config/pipeline-configmap.yaml || true

              if [ ! -f /app/request-data/.code_initialized ]; then
                echo "[init] Copying code from /code to /app/request-data ..."
                cp -r /code/* /app/request-data/
                touch /app/request-data/.code_initialized
                chown -R 1000:1000 /app/request-data
                chmod -R u+w /app/request-data
              fi
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: request-data
              mountPath: /app/request-data
            - name: request-producer-data
              mountPath: /app/request-producer-data
            - name: shared-config
              mountPath: /config
            - name: config-default
              mountPath: /defaults

      containers:
        - name: request-container
          image: sjafari2/kafkaconfluentrequest:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          workingDir: /app/request-data
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              mkdir -p ./logs
              echo "Loaded config:"
              cat /config/pipeline-configmap.yaml
              sleep infinity
          ports:
            - containerPort: 8080
              name: request-port
            - containerPort: 9093
              name: req-exp-port
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: request-data
              mountPath: /app/request-data
            - name: request-producer-data
              mountPath: /app/request-producer-data
            - name: shared-config
              mountPath: /config

      volumes:
        - name: request-data
          persistentVolumeClaim:
            claimName: request-data
        - name: request-producer-data
          persistentVolumeClaim:
            claimName: request-producer-data
        - name: shared-config
          persistentVolumeClaim:
            claimName: pipeline-configmap-pvc
        - name: config-default
          configMap:
            name: pipeline-configmap
            items:
              - key: pipeline-configmap.yaml
                path: pipeline-configmap.yaml

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gpu-01.nrp.mghpcc.org

