nodeSelector:
  kubernetes.io/hostname: gpu-04.nrp.mghpcc.org
persistence:
  storageClass: rook-cephfs-east
replicaCount: 3
extraEnvVars:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: KAFKA_LISTENERS
    value: PLAINTEXT://0.0.0.0:9092
  - name: KAFKA_ADVERTISED_LISTENERS
    value: PLAINTEXT://$(POD_NAME).pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092

