{
 "title": "Kafka Dashboard– Per-Consumer Metrics",
 "tags": [
  "kafka",
  "consumer",
  "latency",
  "lag"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "group",
    "label": "Consumer group",
    "query": "label_values(consumer_cpu_percent, group)"
   },
   {
    "name": "client_id",
    "label": "Client ID",
    "query": "label_values(consumer_cpu_percent{group=~\"$group\"}, client_id)"
   }
  ]
 },
 "panels": [
  { "title": "Kafka Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Lag Skew Ratio  (max/sum)",
   "type": "timeseries",
   "description": "Fraction of all lag concentrated in the hottest partition.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(consumer_lag) / sum(consumer_lag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STD of Lag Skew  Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "stddev_over_time(avg(consumer_lag_skew_ratio)[20m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Total Lag",
   "type": "timeseries",
   "description": "Average total number of messages waiting to be processed across all consumers during the experiment. Higher values indicate the system is falling behind the incoming workload.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "\n  sum(consumer_total_lag)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "STD of System Total Lag ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "stddev_over_time(\n  (sum(consumer_total_lag))[$__range:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 System Latency",
   "type": "timeseries",
   "description": "99th percentile end-to-end latency. Captures extreme latency events and is often used to evaluate worst-case user experience",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "1000 *\nhistogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(consumer_e2e_latency_seconds_bucket[30s])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STD of P99 System Latency",
   "type": "timeseries",
   "description": "Average total number of messages waiting to be processed across all consumers during the experiment. Higher values indicate the system is falling behind the incoming workload.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "\n  sum(consumer_total_lag)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Estimated Per-partition Arrival Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (partition) (\n  rate(producer_partition_messages_total[30s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Consumers Rebalances ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "increase(consumer_rebalances_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer CPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "producer_cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max System Lag",
   "type": "timeseries",
   "description": "Largest total backlog observed during the experiment. Represents the worst congestion level reached by the pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "max(consumer_total_lag)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer CPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "avg by (pod) (consumer_cpu_percent{group=~\"$group\", client_id=~\"$client_id\"})",
     "legendFormat": "{{group}}/{{client_id}}"
    }
   ]
  },
  {
   "title": "Consumer Lag Skew Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    { "expr": "consumer_lag_skew_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mean System Throughput",
   "type": "timeseries",
   "description": "Average number of messages processed per second by all consumers combined. Measures overall processing capacity of the pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "avg_over_time(sum(consumer_total_lag)[15m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STD of Producers Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "stddev_over_time(sum(rate(producer_messages_sent_total[30s]))[20m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(consumer_messages_consumed_total[30s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total lag per consumer",
   "type": "timeseries",
   "description": "For each pod, add lag from all assigned partitions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  consumer_lag\n)",
     "legendFormat": "{{group}}/{{client_id}}"
    }
   ]
  },
  {
   "title": "p90 End to End Latency per Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "1000 *\nhistogram_quantile(\n  0.90,\n  sum by (pod, le) (\n    rate(consumer_e2e_latency_seconds_bucket[30s])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Memory Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "producer_memory_percent",
     "legendFormat": "{{group}}/{{client_id}} {{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Memory Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "avg by (pod) (consumer_memory_percent{group=~\"$group\", client_id=~\"$client_id\"})",
     "legendFormat": "{{group}}/{{client_id}}"
    }
   ]
  },
  {
   "title": "p99 End to End Latency per Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "1000 *\nhistogram_quantile(\n  0.99,\n  sum by (pod, le) (\n    rate(consumer_e2e_latency_seconds_bucket[30s])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}