apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-config
  namespace: kafkastreamingdata
data:
  jmx-kafka-prometheus.yml: |-
    # Tell the exporter which JMX endpoint to scrape (Kafka exposes it on 5555)
    hostPort: 127.0.0.1:5555
    # Alternatively:
    # jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi

    startDelaySeconds: 0
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true

    rules:
      - pattern: 'kafka.server<type=KafkaRequestHandlerPool, name=RequestHandlerAvgIdlePercent><>Value'
        name: kafka_requesthandler_avg_idle_percent
        type: GAUGE
      - pattern: 'kafka.network<type=Processor, name=IdlePercent, networkProcessor=(.+)><>Value'
        name: kafka_network_processor_idle_percent
        labels: { processor: "$1" }
        type: GAUGE
      - pattern: 'kafka.network<type=RequestChannel, name=RequestQueueTimeMs><>99thPercentile'
        name: kafka_request_queue_time_ms_p99
        type: GAUGE
      - pattern: 'kafka.network<type=RequestChannel, name=ResponseQueueTimeMs><>99thPercentile'
        name: kafka_response_queue_time_ms_p99
        type: GAUGE
      - pattern: 'kafka.server<type=BrokerTopicMetrics, name=BytesInPerSec><>OneMinuteRate'
        name: kafka_broker_bytes_in_per_sec
        type: GAUGE
      - pattern: 'kafka.server<type=BrokerTopicMetrics, name=BytesOutPerSec><>OneMinuteRate'
        name: kafka_broker_bytes_out_per_sec
        type: GAUGE
      - pattern: 'kafka.log<type=LogFlushStats, name=LogFlushRateAndTimeMs><>99thPercentile'
        name: kafka_log_flush_time_ms_p99
        type: GAUGE
      - pattern: 'kafka.server<type=ReplicaManager, name=IsrShrinksPerSec><>Count'
        name: kafka_isr_shrinks_total
        type: COUNTER
      - pattern: 'kafka.server<type=ReplicaManager, name=IsrExpandsPerSec><>Count'
        name: kafka_isr_expands_total
        type: COUNTER
      - pattern: 'kafka.network<type=RequestMetrics, name=RequestsPerSec, request=(.+)><>Count'
        name: kafka_requests_total
        labels: { request: "$1" }
        type: COUNTER

