apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-admin
  namespace: kafkastreamingdata
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-admin-role
  namespace: kafkastreamingdata
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-admin-binding
  namespace: kafkastreamingdata
subjects:
- kind: ServiceAccount
  name: pipeline-admin
  namespace: kafkastreamingdata
roleRef:
  kind: Role
  name: pipeline-admin-role
  apiGroup: rbac.authorization.k8s.io

