apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-merge-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: "app/app-merge-data"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - dtn-01.nrp.mghpcc.org
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-merge-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
