apiVersion: v1
kind: PersistentVolume
metadata:
  name: merged-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-east
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  hostPath:
    path: "app/merged-data"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gpu-04.nrp.mghpcc.org
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: merged-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-east
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
status: {}
