apiVersion: v1
kind: PersistentVolume
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-data
  name: producer-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-east
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: "app/producer-data"
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - gpu-04.nrp.mghpcc.org  
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-claim-data
  name: producer-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-east
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
status: {}
