apiVersion: v1
kind: PersistentVolume
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-data
  name: request-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: "app/request-data"
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - dtn-01.nrp.mghpcc.org  
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-claim-data
  name: request-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
