apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-test-pvc-central
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block-central

