apiVersion: v1
kind: Service
metadata:
  labels: 
    app: request 
  name: request-headless-svc
  namespace: kafkastreamingdata
spec:
  clusterIP: None  # 👈 this makes it headless
  selector:
    app: request-sts
  ports:
    - name: request-port
      port: 80         # Service port
      targetPort: 8080 # Matches containerPort in StatefulSet

