apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: kafkastreamingdata
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kafka-pipeline'
        metrics_path: /metrics
        scrape_interval: 15s
        static_configs:
          - targets:
              - producer-headless-svc:8000
              - consumer-headless-svc:8000
              - merge-headless-svc:8000
      
      - job_name: 'kafka-brokers'
        static_configs:
          - targets:
            - pip-kafka-controller-0.pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:7071
            - pip-kafka-controller-1.pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:7071
            - pip-kafka-controller-2.pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:7071
