global:
  storageClass: "rook-cephfs-east"

sasl:
  enabledMechanisms: PLAIN
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  interbroker:
    user: interbrokeruser
    password: "inter123"
  controller:
    user: controlleruser
    password: "controller123"
  client:
    users:
      - user1
    passwords:
      - "5x4XjjbPod"

listeners:
  client:
    name: CLIENT
    containerPort: 9092
    protocol: SASL_PLAINTEXT
    sslClientAuth: ""
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: SASL_PLAINTEXT
    sslClientAuth: ""
  interbroker:
    name: INTERNAL
    containerPort: 9094
    protocol: SASL_PLAINTEXT
    sslClientAuth: ""
  external:
    name: EXTERNAL
    containerPort: 9095
    protocol: SASL_PLAINTEXT
    sslClientAuth: ""

kraft:
  enabled: true
  controllerListenerNames: CONTROLLER
  processRoles: controller,broker

controller:
  jaas:
    user: controlleruser
    password: "controller123"
  replicaCount: 3
  nodeSelector:
    kubernetes.io/hostname: gpu-04.nrp.mghpcc.org
  initContainers:
    - name: volume-permission-fix
      image: busybox
      command:
        - sh
        - -c
        - chown -R 1001:1001 /bitnami/kafka
      volumeMounts:
        - name: data
          mountPath: /bitnami/kafka

  persistence:
    enabled: true
    storageClass: "rook-cephfs-east"
    accessModes:
      - ReadWriteOnce
    size: 300Gi   

  extraEnvVars:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: KAFKA_CFG_NODE_ID
      value: "{{ .StatefulSetOrdinal }}"
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: >-
        CLIENT://$(HOSTNAME).pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092,
        INTERNAL://$(HOSTNAME).pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9094,
        EXTERNAL://$(HOSTNAME).pip-kafka-controller.kafkastreamingdata.svc.cluster.local:9095
    - name: KAFKA_CONTROLLER_QUORUM_VOTERS
      value: "0@pip-kafka-controller-0.pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9093,1@pip-kafka-controller-1.pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9093,2@pip-kafka-controller-2.pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9093"

  extraConfig: |
    delete.topic.enable=true
    auto.create.topics.enable=true
    listener.security.protocol.map=CLIENT:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
    listeners=CLIENT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:9094,EXTERNAL://0.0.0.0:9095
    inter.broker.listener.name=INTERNAL
    sasl.enabled.mechanisms=PLAIN
    sasl.mechanism.inter.broker.protocol=PLAIN
    listener.name.controller.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="controlleruser" password="controller123";
    listener.name.internal.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="interbrokeruser" password="inter123";
    listener.name.client.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="5x4XjjbPod";
    listener.name.external.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="5x4XjjbPod";

    # New cleanup and stability settings:
    log.retention.ms=60000
    log.retention.check.interval.ms=10000
    log.segment.bytes=1048576
    message.max.bytes=1048576
    # Optional size-based retention:
    #log.retention.bytes=10737418240

  resources:
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 4
      memory: 8Gi

