global:
  storageClass: "rook-ceph-block-central"

sasl:
  enabledMechanisms: ""
  interBrokerMechanism: ""
  controllerMechanism: ""
  interbroker:
    user: ""
    password: ""
  controller:
    user: ""
    password: ""
  client:
    users: []
    passwords: []

listeners:
  client:
    name: CLIENT
    containerPort: 9092
    protocol: PLAINTEXT
    sslClientAuth: ""
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
    sslClientAuth: ""
  interbroker:
    name: INTERNAL
    containerPort: 9094
    protocol: PLAINTEXT
    sslClientAuth: ""
  external:
    name: EXTERNAL
    containerPort: 9095
    protocol: PLAINTEXT
    sslClientAuth: ""

kraft:
  enabled: true
  controllerListenerNames: CONTROLLER
  processRoles: controller,broker

controller:
  replicaCount: 3

    #affinity:
    #podAntiAffinity:
    #  requiredDuringSchedulingIgnoredDuringExecution:
    #    - labelSelector:
    #        matchExpressions:
    #          - key: app.kubernetes.io/name
    #            operator: In
    #            values:
    #              - kafka
    #              - producer
    #              - consumer
    #      topologyKey: "kubernetes.io/hostname"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - patternlab.calit2.optiputer.net

  initContainers:

    - name: volume-permission-fix
      image: busybox
      command:
        - sh
        - -c
        - chown -R 1001:1001 /bitnami/kafka
      volumeMounts:
        - name: data
          mountPath: /bitnami/kafka
  persistence:
    enabled: true
    storageClass: "rook-ceph-block-central"
    accessModes:
      - ReadWriteOnce
    size: 300Gi

  extraEnvVars:
    
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    
    - name: KAFKA_CFG_NODE_ID
      value: "{{ .StatefulSetOrdinal }}"
    
    - name: KAFKA_CONTROLLER_QUORUM_VOTERS
      value: "0@pip-kafka-controller-0.pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9093,1@pip-kafka-controller-1.pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9093,2@pip-kafka-controller-2.pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9093"
    
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: >-
        CLIENT://$(HOSTNAME).pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092,
        INTERNAL://$(HOSTNAME).pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9094,
        EXTERNAL://$(HOSTNAME).pip-kafka-controller.kafkastreamingdata.svc.cluster.local:9095
    
  extraConfig: |
    delete.topic.enable=true
    auto.create.topics.enable=true
    listener.security.protocol.map=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    listeners=CLIENT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:9094,EXTERNAL://0.0.0.0:9095
    advertised.listeners=CLIENT://$(HOSTNAME).pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092,INTERNAL://$(HOSTNAME).pip-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9094,EXTERNAL://$(HOSTNAME).pip-kafka-controller.kafkastreamingdata.svc.cluster.local:9095
    inter.broker.listener.name=INTERNAL

    # Performance tuning
    log.retention.ms=180000
    log.retention.check.interval.ms=10000
    log.segment.bytes=134217728
    log.segment.ms=30000
    message.max.bytes=1048576
    num.network.threads=8
    num.io.threads=16
    log.flush.interval.messages=1000000
    log.flush.interval.ms=10000
    queued.max.requests=5000
    socket.request.max.bytes=104857600
    replica.fetch.max.bytes=10485760
    replica.fetch.response.max.bytes=10485760
    replication.factor=2
    min.insync.replicas=1
    offsets.topic.replication.factor=2
    # Metadata refresh & retry handling
    connections.max.idle.ms=300000
    metadata.max.age.ms=300000                    
    request.timeout.ms=30000
    retries=5
    retry.backoff.ms=1000                         
  resources:
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 4
      memory: 8Gi

auth:
  sasl:
    enabled: false

zookeeper:
  enabled: false
