apiVersion: v1
kind: Service
metadata:
  name: consumer-headless-svc
  namespace: kafkastreamingdata
  labels:
    app: consumer-sts
spec:
  clusterIP: None  # Headless service for stable pod DNS
  selector:
    app: consumer-sts
  ports:
    #- name: consumer-port
    #  port: 80
    #  targetPort: 8080
    #- name: application-port
    #  port: 81
    #  targetPort: 8081
    - name: metrics
      port: 8000       # what Prometheus dials
      targetPort: 8000  # must match app's listening port
