apiVersion: v1
kind: Service
metadata:
  labels: 
    app: merge
  name: merge-headless-svc
  namespace: kafkastreamingdata
spec:
  clusterIP: None  # 👈 this makes it headless
  selector:
    app: merge-sts
  ports:
    - name: merge-pport
      port: 80         # Service port
      targetPort: 8080 # Matches containerPort in StatefulSet

