apiVersion: v1
kind: Service
metadata:
  name: producer-headless-svc
  namespace: kafkastreamingdata
  labels:
    app: producer-sts       # 👈 metadata label (informational only)

spec:
  clusterIP: None  # ← Headless!
  selector:
    app: producer-sts
  ports:
    #- name: producer-port
    #  port: 80
    #  targetPort: 8080
    - name: metrics
      port: 8001        # what Prometheus dials
      targetPort: 8001  # must match app's listening port
