apiVersion: v1
kind: Service
metadata:
  labels: 
    app: request-svc 
  name: request-svc
  namespace: kafkastreamingdata
spec:
  type: ClusterIP
  selector:
    app: request-sts  
  ports:
    - protocol: TCP
      port: 80         # Service external port
      targetPort: 8080  # This should match the containerPort of request-sts-0 pod 
