apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-configmap
data:
  KAFKA_TOPIC_COUNT: "10"
  KAFKA_INSTALL_PATH: "/kafka/bin/"

  PRODUCER_COUNT: "2"
  PRODUCER_TOPIC_COUNT: "10"
  PRODUCER_INPUT_PATH: "request-producer-data"
  PRODUCER_POD_COUNT: "2"
  WAITE_TIME: "2"
  BATCH_SIZE: "100"
  TOPIC_TITLE: "synthetic"
  NUM_PARTITIONS: "10"
  REPLICATION_FACTOR: "1"
  DELAY_BETWEEN_MESSAGES: "0"
  RANDOM_RANGE: "50000"
  LINGER_MS: "100"
  COMPRESSION_TYPE: "lz4"
  MAX_REQUEST_SIZE: "2097152"
  ACKS: "1"

  OFFSET_RESET: "earliest"
  ENABLE_AUTO_COMMIT: "False"
  MAX_MESSAGES: "500"
  group_id: "Streaming"
  max_in_flight_requests_per_connection: "5"
  auto_commit_interval_ms: "10000"
  enable.idempotence: "True"
  CONSUMER_POD_COUNT: "2"
  CONSUMER_COUNT: "2"
  CONSUMER_WINDOW_COUNT: "2"

  APPLICATION_WAIT_TIME: "5"
  APPLICATION_COUNT: "2"

  REQUEST_COUNT: "1"
  RequestURL: "http://127.0.0.1:8080/"
  RequestInputPath: "./request-data/simulator"
  RequestOutputPath: "./request-producer-data"
  StartDate: "2022-8-01-00"
  EndDate: "2022-8-01-05"
  RequestWindow: "hour"
  Wait: "5"
  RqstPodMntPath: "request-data"
  RqstPodSharedPath: "request-producer-data"

  MERGE_COUNT: "1"
  MERGE_WAIT_TIME: "60"
  MERGE_WAIT_THRESHOLD: "5"
  merge_path: "./merged-data"

