apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consumer-merge-cephfs
  namespace: kafkastreamingdata
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-ucsd   # RWX, low-latency in UCSD zone
  resources:
    requests:
      storage: 300Gi

