apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consumer-merge-data
  namespace: kafkastreamingdata
spec:
  storageClassName: rook-cephfs-central 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi

