apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-broker-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi

