apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-configmap-pvc
  namespace: kafkastreamingdata
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

