apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: producer-data
  namespace: kafkastreamingdata
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

